### ISSUE TITLE
Renaissance Specification Papers

### ISSUE THREAD

**Issue by ghost** [GreenPix/meta#4]
Hi everyone.

Rather than RFC, I propose to call our specification “Renaissance Specification Paper”, that is RSP. I intend to write the maybe-called RSP-0, that is how to write a RSP. The RSP-1 should be the one that describe the AaribaScript.

What do you think?

**Comment by Nemikolh** [comment]
I'm 100% in agreement with that. I actually felt the term 'RFC' to be strange in our context (That's one of the reason why I had used the word "proposal", but it didn't sound good either  :smile:).

I really like your naming !

When everyone has agreed, I think you can update right away the repository, no need for a PR for that.

**Comment by ghost** [comment]
> I really like your naming !

Naming is what I do ;D.

**Comment by ghost** [comment]
Well, unsurprisingly I don't have any other naming proposal, so agreed :)

**Comment by ghost** [comment]
RSP it is!
